# Generated by Django 4.1.4 on 2022-12-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0003_remove_manager_customuser_ptr_customuser_is_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='фото'),
        ),
    ]
