# Generated by Django 4.1.4 on 2022-12-09 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0004_alter_smscode_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='salon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='masters', to='beauty_salon.salon', verbose_name='салон'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='master',
            field=models.ManyToManyField(null=True, related_name='procedures', to='beauty_salon.master', verbose_name='мастера'),
        ),
        migrations.AlterField(
            model_name='schedulepoint',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_points', to='beauty_salon.master', verbose_name='мастер'),
        ),
        migrations.AlterField(
            model_name='schedulepoint',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('busy', 'busy')], default='available', max_length=10, verbose_name='статус'),
        ),
    ]
