# Generated by Django 4.1.4 on 2022-12-10 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0004_customuser_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='master',
        ),
        migrations.AddField(
            model_name='entry',
            name='time_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='time_entries', to='beauty_salon.schedulepoint', verbose_name='время записи'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='фото'),
        ),
    ]
