# Generated by Django 4.1.4 on 2022-12-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0005_remove_entry_master_entry_time_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulepoint',
            name='date',
            field=models.DateField(verbose_name='дата записи'),
        ),
    ]
