# Generated by Django 4.1.4 on 2022-12-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0005_alter_master_salon_alter_procedure_master_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='master',
            field=models.ManyToManyField(related_name='procedures', to='beauty_salon.master', verbose_name='мастера'),
        ),
    ]
